print("\nThe rules of this game is to beat the dealer having a hand value close to 21 without going over")
print("\nNumber cards are (2-10)")
print("\nFace Cards are worth 10 points (jack, queen and king)")
print("\nAce cards are either 1 or 11 (your choice)")
print("\nThe player and the dealer will recieve two cards")
print("\nPlayer's cards are face up while the dealer has one face up and one face down")
print("\nIt is the player's turn now")
print("\nChoices are :Stand,Hit,Split")
print("\nThey can hit (take another card, but if they go over 21 they lose)")
print("\nSplit if the two cards are the same value then you split them in two seperate hands")
print("\nNow it is the dealers turn")
print("\nTheir only choice is to keep hitting until the dealer is above 16")
print("\nBut if dealer goes over 21 he busts and loses")
print("\nIf the player hits 21 but the dealer has below 21 player wins")
print("\nIf player is closer to 21 then the dealer without going over player wins")
print("\nIf dealer hits 21 but player has below 21 dealer wins")
print("\nIf dealer is closer to 21 then player loses😭")
print("\nIf player and dealer get the same number it is a draw(❁´◡`❁)")
print("\nThen shuffle the cards and repeat👌.")